version: "3"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3332:3306
        volumes: 
            - ./data/mysql:/var/lib/mysql
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes: 
            - ./data/mongo:/data/db
