version: "3"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        ports:
            - 3332:3306
        volumes: 
            - ./data/mysql:/var/lib/mysql
